services:
  ak4q8x2m7v:
    container_name: ak4q8x2m7v_app
    image: ghcr.io/mr-devloper005/aporiakennels.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3083:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
